const V="gym-v1";
const CORE=["./", "index.html", "manifest.webmanifest", "icon-180.png", "icon-192.png", "icon-512.png"];
const IMGS=["img/cruces_polea_0.jpg", "img/cruces_polea_1.jpg", "img/crunch_polea_0.jpg", "img/crunch_polea_1.jpg", "img/curl_barra_0.jpg", "img/curl_barra_1.jpg", "img/curl_femoral_0.jpg", "img/curl_femoral_1.jpg", "img/curl_martillo_0.jpg", "img/curl_martillo_1.jpg", "img/dominadas_0.jpg", "img/dominadas_1.jpg", "img/elev_lat_0.jpg", "img/elev_lat_1.jpg", "img/elev_piernas_0.jpg", "img/elev_piernas_1.jpg", "img/extension_cuad_0.jpg", "img/extension_cuad_1.jpg", "img/face_pull_0.jpg", "img/face_pull_1.jpg", "img/fondos_0.jpg", "img/fondos_1.jpg", "img/gemelos_0.jpg", "img/gemelos_1.jpg", "img/hip_thrust_0.jpg", "img/hip_thrust_1.jpg", "img/jalon_0.jpg", "img/jalon_1.jpg", "img/peso_muerto_0.jpg", "img/peso_muerto_1.jpg", "img/peso_muerto_rumano_0.jpg", "img/peso_muerto_rumano_1.jpg", "img/prensa_0.jpg", "img/prensa_1.jpg", "img/press_banca_0.jpg", "img/press_banca_1.jpg", "img/press_frances_0.jpg", "img/press_frances_1.jpg", "img/press_hombro_manc_0.jpg", "img/press_hombro_manc_1.jpg", "img/press_incl_manc_0.jpg", "img/press_incl_manc_1.jpg", "img/press_militar_0.jpg", "img/press_militar_1.jpg", "img/remo_barra_0.jpg", "img/remo_barra_1.jpg", "img/remo_manc_0.jpg", "img/remo_manc_1.jpg", "img/remo_polea_0.jpg", "img/remo_polea_1.jpg", "img/sentadilla_0.jpg", "img/sentadilla_1.jpg", "img/triceps_polea_0.jpg", "img/triceps_polea_1.jpg", "img/zancada_bulgara_0.jpg", "img/zancada_bulgara_1.jpg"];
self.addEventListener("install",e=>{e.waitUntil(caches.open(V).then(c=>c.addAll(CORE).then(()=>c.addAll(IMGS).catch(()=>{}))).then(()=>self.skipWaiting()))});
self.addEventListener("activate",e=>{e.waitUntil(caches.keys().then(ks=>Promise.all(ks.filter(k=>k!==V).map(k=>caches.delete(k)))).then(()=>self.clients.claim()))});
self.addEventListener("fetch",e=>{
  const r=e.request;if(r.method!=="GET")return;
  if(r.mode==="navigate"){e.respondWith(fetch(r).then(res=>{const cp=res.clone();caches.open(V).then(c=>c.put("index.html",cp));return res}).catch(()=>caches.match("index.html")));return}
  e.respondWith(caches.match(r).then(hit=>hit||fetch(r).then(res=>{if(res.ok&&(r.url.startsWith(self.location.origin)||r.url.includes("fonts.g"))){const cp=res.clone();caches.open(V).then(c=>c.put(r,cp))}return res})));
});
